version: '3'
services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - server-side

  postgres:
    container_name: postgres
    restart: always
    image: postgres:15.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - server-side

  zero2prod:
    build: .
    container_name: zero2prod
    restart: always
    links:
      - postgres
    ports:
      - "8000:8000"
    tty: true
    networks:
      - server-side
    volumes:
      - ./src:/code/src
      - backend-cache:/code/target
    depends_on:
      - postgres

networks:
  server-side:
    driver: bridge

volumes:
  backend-cache: {}
  db-data: {}